server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://139.9.100.22:3306/mason?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
